### ISSUE TITLE
Use owned strings instead of string slices for request parameters

### ISSUE THREAD

**Issue by mre** [SimonPersson/ease#11]
I'm writing a new API wrapper using ease and I've had a fun time so far.  
For testing I use [mockers](https://github.com/kriomant/mockers), which is a mocking library for Rust.

Right now I've hit a roadblock because mockers [doesn't support non-'static lifetimes](https://github.com/kriomant/mockers#limitations). The request parameters in ease have the following type, though:

``` rust
params: Option<Vec<(&'a str, &'a str)>>
```

As a workaround I wanted to use `Vec<(String, String)>` as a datatype inside my library and convert the parameters to `Vec<(&'a str, &'a str)>` right before I pass them to ease:

``` rust
fn do_request<'a>(&'a self,
                  endpoint: String,
                  params: Vec<(String, String)>)
                  -> Result<ease::Response, ease::Error> {
    let url = ease::Url::parse(&endpoint).unwrap();
    let params_new: Vec<(&'a str, &'a str)> =
        params.iter().map(|&(ref a, ref b)| (&a[..], &b[..])).collect();
    ease::Request::new(url).params(params_new).get()
}
```

Besides the fact that this is quite verbose, it also doesn't work because I run into lifetime issues. (`params` needs to live for the lifetime `'a`.)

One solution would be to also allow  `Vec<(String, String)>` as request parameters in ease. 
We could still support `Vec<(&'a str, &'a str)>` by using [the `Into`-trait](http://hermanradtke.com/2015/05/06/creating-a-rust-function-that-accepts-string-or-str.html).

**Advantages:**
- Support owned strings and string slices without requiring conversions (backward compatible).
- Avoid dealing with lifetimes when using ease.

**Disadvantages:**
- Runtime performance overhead by converting string slices to owned Strings. (Although this might be a tiny overhead. Network overhead would be much bigger.)

I would create a pull request if you like this proposal. :smiley:

**Comment by SimonTeixidor** [comment]
I agree that network overhead is much larger than the overhead of converting `&str` to `String`. I would welcome a PR that implements this :+1:
