### ISSUE TITLE
explain cookie handling with ease

### ISSUE THREAD

**Issue by silvio** [SimonPersson/ease#2]
I have a server with access via username/passwd. It returns a session cookie. How I handle this situation with `ease`?

**Comment by SimonTeixidor** [comment]
`ease` does not have any special support for cookies at the moment. However, `hyper` does support cookies so you can get the cookie from the [`HyperResponse`](http://simonpersson.github.io/ease/hyper/client/response/struct.Response.html) in `Response`. Something like this might work, but I haven't tested it (import `Cookie` from `hyper`):

``` rust
response.hyper_response.headers.get::<Cookie>()
```

Now this is a fairly common use case I guess, so if this work I'll add a convenience method to `Response` that does basically this to simplify it a bit. Thanks for raising the issue :)
