### ISSUE TITLE
Code at crates.io doesn't match the documentation

### ISSUE THREAD

**Issue by imp** [SimonPersson/ease#5]
It looks like the latest commit that changes `json_as()` to `from_json()` didn't make it to crates.io I've spent many hours trying to figure out why 

```
src/lib.rs:46:71: 46:98 error: no method named `from_json` found for type `ease::Response` in the current scope
src/lib.rs:46         println!("{:#?}", Request::new(url).post().and_then(|res| res.from_json::<PostResponse>()));
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

until I realised it uses `json_as()`

**Comment by SimonTeixidor** [comment]
Ouch, I'm sorry for that! This repos hasn't gotten the love it needs. I'll publish the new version to crates.io!

**Comment by SimonTeixidor** [comment]
Okay, `serde_macros` doesn't build which breaks tests on nightly. I'll push the change as soon as that's been fixed so I can bump the version of that dependency.

**Comment by SimonTeixidor** [comment]
Here we go! The `serde` developers merged my PR so that this builds again. I've pushed a new version to crates.io. Sorry for the inconvenience!
