### ISSUE TITLE
Support request timeout 

### ISSUE THREAD

**Issue by mre** [SimonPersson/ease#6]
Hi!

It would be cool if we could support HTTP request timeouts like so:
https://github.com/hyperium/hyper/blob/ce3dbd123d9cd10f4f1e09392ba6f3e4ac949d98/tests/client.rs#L252

It's a minor thing but might be worth adding.
Thanks for your library!

**Comment by SimonTeixidor** [comment]
That sounds useful! I can take a look at it in a week or so as I'm away from my development machine right now. Or you could send a pull request and I'll take a look right away.

**Comment by SimonTeixidor** [comment]
I've pushed a new commit to add this feature, and updated the documentation. Feel free to reopen if your issue is not solved!

**Comment by mre** [comment]
Sweet. Thanks!
