### ISSUE TITLE
How do I specify headers?

### ISSUE THREAD

**Issue by philippkeller** [SimonPersson/ease#8]
I'd like to send a Authentication header with the request, I tried it this way:

```
extern crate ease;
extern crate hyper;

use ease::{Url, Request, Header};
use hyper::header::Authorization;

fn main() {
    let auth = "Access-Token my_long_token".to_owned();
    let url = Url::parse("https://api.robinpowered.com/v1.0/auth").unwrap();
    Request::new(url).header(Authorization(auth)).get();
}
```

but I get this as an error:

```
main.rs:10:23: 10:29 error: the trait bound `hyper::header::Authorization<std::string::String>: ease::Header` is not satisfied [E0277]
main.rs:10     Request::new(url).header(Authorization(auth)).get();
                                 ^~~~~~
```

I'm new to rust, but how I read the error is that hyper::Header is incompatible to ease::Header which in fact would be the same if I could reference Authorization somehow via ease::.. but since this is not exposed I need to add the hyper dependency myself and this causes the error.

Any hints on how to solve this?
First I had this:

```
let mut headers = Headers::new();
headers.set_raw("Authorization", vec![app_token.to_vec()]);
let url = Url::parse("https://api.robinpowered.com/v1.0/auth").unwrap();
Request::new(url).header(Authorization(app)).get()
```

but that also didn't work since `Request::header` takes `Header` but I'm passing a `Headers`

**Comment by SimonTeixidor** [comment]
I think your issue is that you got two different versions of Hyper, one as a dependency of your application and one as a dependency of Ease. Mt fault really, as I forgot to re-export the headers, so that you had to pull in the Hyper dependency manually in the first place :) I've published a new version with the headers re-exported. This code now compiles:

```
extern crate ease;

use ease::{Url, Request};
use ease::header::Authorization;

fn main() {
    let auth = "Access-Token my_long_token".to_owned();
    let url = Url::parse("https://api.robinpowered.com/v1.0/auth").unwrap();
    Request::new(url).header(Authorization(auth)).get();
}
```

I'll close this issue, feel free to open if it isn't solved for you.

**Comment by philippkeller** [comment]
thanks a lot for the quick fix! It's compiling (&working!) now. I was already planning to rewrite my code to use Hyper directly, but with your crate it's a lot better (and easier) now
